### ISSUE TITLE
Pull out Mistral prompt into template

### ISSUE THREAD

**Issue by veekaybee** [mozilla-ai/lumigator#124]
https://docs.mistral.ai/guides/prompting_capabilities/#summarization

**Comment by kernel-loophole** [comment]
HI @veekaybee @aittalam pull the template from the mistral.
here are the changes https://github.com/mozilla-ai/lumigator/compare/main...kernel-loophole:lumigator:main

**Comment by veekaybee** [comment]
Thanks for sharing this @kernel-loophole! We're currently not planning on changing the prompt template as-is but this is great to have for reference. For some context behind this issue, we'd like to eventually try out Mistral's summarization prompt, but the other component of that is we want people to be able to also pass a prompt by default when evaluating, which this issue doesn't explain clearly. So this issue is actually two things: 

1. We'd like to change the Mistral prompt in the future to re-evaluate summarization AND
2. We'd like customization of prompts to work for folks

I've filed a clearer issue for this https://github.com/mozilla-ai/lumigator/issues/395

**Comment by kernel-loophole** [comment]
Thanks for the clarification and context @veekaybee  It's great to know the broader goals behind this.  Appreciate it. Let me know if there's anything I can contribute!
