### ISSUE TITLE
Pass the command as a parameter to submissions

### ISSUE THREAD

**Issue by ividal** [mozilla-ai/lumigator#232]
**Is your feature request related to a problem? Please describe.**
Currently ray job submissions are tied to an lm-buddy evaluation job. It would be preferable to be able to pass any command as a parameter.

**Describe the solution you'd like**
Be able to use python code other than lm-buddy in submissions.

**Describe alternatives you've considered**
Other hard-coded submissions.

**Additional context**

**Comment by aittalam** [comment]
Addressed with [PR248](https://github.com/mozilla-ai/lumigator/pull/248)
