### ISSUE TITLE
Add support for seq2seq models with transformers or vLLM as-a-library

### ISSUE THREAD

**Issue by ividal** [mozilla-ai/lumigator#339]
This inference mode calls on hf transformers to run the model, rather than sending a request to an external API.

For context, users will likely want to compare models they can get from HF model hub, for example. This means running the model ad-hoc for a task, rather than sending a request to an external API.

**Comment by javiermtorres** [comment]
Using the models in https://huggingface.co/hf-internal-testing would be great for testing. Do you know if vLLM supports any of those? Could we use them somehow without much additional effort? Thanks a lot :)
