### ISSUE TITLE
CI fails with "username and password required" error.

### ISSUE THREAD

**Issue by aittalam** [mozilla-ai/lumigator#343]
**Describe the bug**
[This PR](https://github.com/mozilla-ai/lumigator/pull/321) and [this PR ](https://github.com/mozilla-ai/lumigator/pull/335) (both coming from forks) fail on CI with a "username and password required" error (respectively [here](https://github.com/mozilla-ai/lumigator/actions/runs/11745660850/job/32724150542?pr=321) and [here](https://github.com/mozilla-ai/lumigator/actions/runs/11635883764/job/32406163535?pr=335)). Is it something we should fix in our actions?

**To Reproduce**
Open one of the two PRs and try re-running checks

**Expected behavior**
Checks work even from forked repos

**Comment by agpituk** [comment]
Hi @aittalam  , should we close this one after merging https://github.com/mozilla-ai/lumigator/pull/346?

**Comment by aittalam** [comment]
Yes, we tested this live and it works properly. Many thanks @agpituk !
