### ISSUE TITLE
Testing: Separate unit tests from integration tests

### ISSUE THREAD

**Issue by ividal** [mozilla-ai/lumigator#373]
Ideally we should move integration tests to a separate place, and allow unit tests to live near the code.

Currently they’re mixed together and a lot of tests rely on PyTest providing dependencies to tests that are essentially spinning up the backend app (as if it’s real).

Unit tests and integration tests will be stored in separate directories and triggered by different targets in the Makefile.

**Comment by javiermtorres** [comment]
This is applicable for both backend and SDK (SDK being slightly more separated right now).
