### ISSUE TITLE
job-all.json file does not capture current API

### ISSUE THREAD

**Issue by aittalam** [mozilla-ai/lumigator#393]
**Describe the bug**
The [job-all.json](https://github.com/mozilla-ai/lumigator/blob/main/lumigator/python/mzai/sdk/tests/data/job-all.json) file does not capture the current API, which means some of its data is not really used by tests (as they would fail otherwise).

**System Information (please complete the following information):**
 - Lumigator version : [2a6f8f7](https://github.com/mozilla-ai/lumigator/commit/2a6f8f7281bfe3f69ee73863704eca8ed9c8a3e4)

**Expected behavior**
Data in the example JSON should reflect the current API syntax and tests should return an error otherwise

**Screenshots**
Example: "config_infer_template" and "config_eval_template" do not exist anymore

**Comment by javiermtorres** [comment]
Ok, but should I add the extra=forbid in a moment and just check the tests? It should be quick to do.

**Comment by javiermtorres** [comment]
You can see it failing now :)
https://github.com/mozilla-ai/lumigator/actions/runs/11916963413/job/33210860682?pr=396
I'll add the forbid param and clean up the tests.
