### ISSUE TITLE
[FEATURE]: Save inference output as a dataset which can be downloaded

### ISSUE THREAD

**Issue by ividal** [mozilla-ai/lumigator#405]
# Motivation

When the user runs an inference job (#339), an extra "field" is calculated containing a model’s predictions. The semantics of this field might be different depending on the purpose inference was used for (e.g., prediction or ground truth generation), but in all cases it is a prediction of a model. Only the user should keep track of what the data was used for.

Inference should create a new dataset, with one extra column containing the model's predictions. This dataset should be stored on object storage and the database should be updated.

# Alternatives

* An idea is to allow the prediction field to be named differently based on whether the job's goal was to generate "ground-truth" or another form of prediction. However, this could lead to errors. To maintain simplicity, we could standardize the output of an inference job to always represent "predictions", leaving it to the user to handle any further differentiation as needed.
* Having MLflow (#438) handle this entirely. Ideally this work would be independent, though: whether there is a tracking service or not, it is reasonable that the inference job stores the output somewhere and returns the URI. Whether this URI is tracked with one service or another is independent.

**Comment by ividal** [comment]
cc @aittalam Heads-up, this is something we can take to Discussions/slack if you prefer. Topics that could be up for debate:
* semantics predictions/ground-triuth
* csv vs other formats (json, for robustness and versatility?)

**Comment by ividal** [comment]
@dpoulopoulos To avoid issues later, this:
> semantics (predictions, ground-truth)

relates to not using "ground-truth", since more often than not we are allowing AI-generated annotations. "Annotation" feels safer. OK with this @aittalam or is there an issue in adopting that naming here already?

**Comment by aittalam** [comment]
> [@dpoulopoulos](https://github.com/dpoulopoulos) To avoid issues later, this:
> 
> > semantics (predictions, ground-truth)
> 
> relates to not using "ground-truth", since more often than not we are allowing AI-generated annotations. "Annotation" feels safer. OK with this [@aittalam](https://github.com/aittalam) or is there an issue in adopting that naming here already?

Thanks for raising this and sorry I missed it! I agree to not using `ground-truth` for synthetic annotations. At this point I'd go with the same term for everything (I am leaning a bit more towards `predictions`, but eventually am fine with anything as long as it's not ambiguous). The main issue with the current eval job is that it'd expect a field called `ground-truth` but I think it's time we get rid of that and just allow both input datasets and fields to be specified with the input config. WDYT?

**Comment by dpoulopoulos** [comment]
When an inference job completes successfully, it generates a `results.json` file. This file already includes the `examples` and `prediction` columns we need. Our task is to create a background process that downloads the file, creates the dataset, and uploads it. All these steps can be performed in memory, eliminating the need for temporary files.

The new dataset's filename will be the original filename with an `-annotated` suffix. For example, `dialogsum.csv` would become `dialogsum-annotated.csv`.

Additionally, two new fields will be added to the database:

- `ai_generated`: Indicates whether the dataset is AI-generated  
- `run_id`: Identifies the run that created the dataset

This is the final schema:

```json
{
  "id": "...",
  "filename": "{dataset_filename}-annotated.csv",
  "format": "job",
  "size": 3603,
  "ground_truth": false,
  "ai_generated": true,
  "run_id": "...",
  "created_at": "2024-12-16T11:56:10"
}
```
