### ISSUE TITLE
Model paths vs URIs

### ISSUE THREAD

**Issue by dpoulopoulos** [mozilla-ai/lumigator#428]
In the codebase, we currently name terms like `hf://...` as "model paths" and "URIs." This inconsistency can cause confusion and make the code harder to read and maintain.

To improve clarity and maintain consistency, we should standardize the naming of this variable. We can either refer to it consistently as `path` or as `URI`.

Let’s decide on the preferred terminology and refactor the code accordingly to avoid ambiguity and ensure better readability across the codebase.

**Comment by aittalam** [comment]
TY Dimitris! For what it's worth, I vote +1 on URIs.

**Comment by javiermtorres** [comment]
+1 to URI!
