### ISSUE TITLE
Add tooltips to Evaluation Results

### ISSUE THREAD

**Issue by hasangzl** [mozilla-ai/lumigator#454]
See design [here](https://www.figma.com/design/JWTS4eGqJv8GRVE0N5hGYw/(WIP)-Lumigator?node-id=3359-7745&node-type=frame&t=qH8AZvb4DJwb75Au-11)

Tooltip descriptions [here](https://docs.google.com/document/d/1meCNaARNYIV27dUr5pBJQdrZf6OEd9NMwt--miPmplE/edit?tab=t.0)

**Comment by george-mzai** [comment]
Working on branch: ` feature/454-tooltips-@results`
